version: 2

jobs:
  test:
    docker: [{image: "perl:5.26"}]
    working_directory: /tmp/pgbadger
    steps:
    - run:
        name: Install debian packages
        command: apt update -y && apt install -y bats git ssh
    - checkout
    - run:
        name: Executing tests
        command: prove

workflows:
  version: 2
  pipeline:
    jobs:
    - test
